const tabData = [
  {
    label: "X1",
    ingredients: [
      { name: "Meat Scraps", type: "Meat", selected: false },
      { name: "Rubbery Jerky", type: "Meat", selected: false },
      { name: "Tough Meat", type: "Meat", selected: false },
      { name: "Chunky Rice", type: "Bran", selected: false },
      { name: "Furahiya Wheat", type: "Bran", selected: false },
      { name: "Mixed Beans", type: "Bran", selected: false },
      { name: "Bone Taco", type: "Fish", selected: false },
      { name: "Clamchip", type: "Fish", selected: false },
      { name: "Scalefish", type: "Fish", selected: false },
      { name: "Oily Raisins", type: "Fruit", selected: false },
      { name: "Jungle Onion", type: "Veggie", selected: false },
      { name: "Pumpkin", type: "Veggie", selected: false },
      { name: "Twinshroom", type: "Veggie", selected: false },
      { name: "Powdered Cheese", type: "Milk", selected: false },
      { name: "Sticky Cream", type: "Milk", selected: false },
      { name: "Hopi", type: "Drink", selected: false },
    ],
    meals:[
      { ingredient1: "Meat", ingredient2: "Meat", effect: "HP +10" },
      { ingredient1: "Meat", ingredient2: "Bran", effect: "HP +10" },
      { ingredient1: "Meat", ingredient2: "Veggie", effect: "Stm +25" },
      { ingredient1: "Meat", ingredient2: "Drink", effect: "Atk (S)" },
      { ingredient1: "Bran", ingredient2: "Bran", effect: "Stm +25" },
      { ingredient1: "Bran", ingredient2: "Fish", effect: "HP +10" },
      { ingredient1: "Bran", ingredient2: "Fruit", effect: "Ice +3" },
      { ingredient1: "Fish", ingredient2: "Fish", effect: "Atk (S)" },
      { ingredient1: "Fish", ingredient2: "Veggie", effect: "Stm +25" },
      { ingredient1: "Fish", ingredient2: "Drink", effect: "Def +10" },
      { ingredient1: "Fruit", ingredient2: "Veggie", effect: "HP +20" },
      { ingredient1: "Fruit", ingredient2: "Milk", effect: "Stm +25" },
      { ingredient1: "Veggie", ingredient2: "Veggie", effect: "Def +10" },
    ],
  },
  {
    label: "X2",
    ingredients: [
      { name: "Cubesteak", type: "Meat", selected: false },
      { name: "Spicy Sausage", type: "Meat", selected: false },
      { name: "Wild Bacon", type: "Meat", selected: false },
      { name: "Hardtack", type: "Bran", selected: false },
      { name: "Snowy Rice", type: "Bran", selected: false },
      { name: "Snake Salmon", type: "Fish", selected: false },
      { name: "Tuna Head", type: "Fish", selected: false },
      { name: "Fruity Jam", type: "Fruit", selected: false },
      { name: "Northern Orange", type: "Fruit", selected: false },
      { name: "Mild Herb", type: "Veggie", selected: false },
      { name: "Sliced Cactus", type: "Veggie", selected: false },
      { name: "Spotted Onion", type: "Veggie", selected: false },
      { name: "Young Potato", type: "Veggie", selected: false },
      { name: "Aged Cheest", type: "Milk", selected: false },
      { name: "Carefree Yogurt", type: "Milk", selected: false },
      { name: "Furahiya Cola", type: "Drink", selected: false }
    ],
    meals: [
      { ingredient1: "Meat", ingredient2: "Meat", effect: "HP +20" },
      { ingredient1: "Meat", ingredient2: "Bran", effect: "Def +15" },
      { ingredient1: "Meat", ingredient2: "Fruit", effect: "Fir +3" },
      { ingredient1: "Meat", ingredient2: "Drink", effect: "HP +10" },
      { ingredient1: "Bran", ingredient2: "Bran", effect: "Stm +25" },
      { ingredient1: "Bran", ingredient2: "Fish", effect: "HP +20" },
      { ingredient1: "Bran", ingredient2: "Veggie", effect: "Atk (S)" },
      { ingredient1: "Bran", ingredient2: "Drink", effect: "HP +10 Thn +3" },
      { ingredient1: "Fish", ingredient2: "Fish", effect: "Atk (S)" },
      { ingredient1: "Fish", ingredient2: "Drink", effect: "Stm +25" },
      { ingredient1: "Fruit", ingredient2: "Veggie", effect: "HP +10 Def +10" },
      { ingredient1: "Fruit", ingredient2: "Milk", effect: "Wtr +3" },
      { ingredient1: "Veggie", ingredient2: "Veggie", effect: "Def +10" },
      { ingredient1: "Veggie", ingredient2: "Drink", effect: "Stm +25" },
      { ingredient1: "Milk", ingredient2: "Milk", effect: "Stm +25 Atk (S)" },
      { ingredient1: "Milk", ingredient2: "Drink", effect: "Ice +3" }
    ],
  },
  {
    label: "X3",
    ingredients:[
      { name: "Great Mutton", type: "Meat", selected: false },
      { name: "Juicy Rib Roast", type: "Meat", selected: false },
      { name: "Meatwagon", type: "Meat", selected: false },
      { name: "Kut Beans", type: "Bran", selected: false },
      { name: "Tasty Rice", type: "Bran", selected: false },
      { name: "Warwheat", type: "Bran", selected: false },
      { name: "Curved Shrimp", type: "Fish", selected: false },
      { name: "Horseshoe Crab", type: "Fish", selected: false },
      { name: "Spiky Blowfish", type: "Fish", selected: false },
      { name: "Frozen Apples", type: "Fruit", selected: false },
      { name: "Cudgel Onion", type: "Veggie", selected: false },
      { name: "Spicy Carrots", type: "Veggie", selected: false },
      { name: "Western Parsley", type: "Veggie", selected: false },
      { name: "Buffalo Butter", type: "Milk", selected: false },
      { name: "Chili Cheese", type: "Milk", selected: false },
      { name: "Panish", type: "Drink", selected: false }
    ],
    meals: [
      { ingredient1: "Meat", ingredient2: "Meat", effect: "HP +20" },
      { ingredient1: "Meat", ingredient2: "Fish", effect: "Thn +3" },
      { ingredient1: "Meat", ingredient2: "Fruit", effect: "Atk (L)" },
      { ingredient1: "Meat", ingredient2: "Veggie", effect: "HP +10 Atk (S)" },
      { ingredient1: "Bran", ingredient2: "Bran", effect: "Stm +25" },
      { ingredient1: "Bran", ingredient2: "Veggie", effect: "Stm +50" },
      { ingredient1: "Bran", ingredient2: "Milk", effect: "Stm +25 Def +10" },
      { ingredient1: "Bran", ingredient2: "Drink", effect: "Def +15 Wtr +3" },
      { ingredient1: "Fish", ingredient2: "Fish", effect: "Atk (S)" },
      { ingredient1: "Fish", ingredient2: "Fruit", effect: "Stm +25 Fir +3" },
      { ingredient1: "Fish", ingredient2: "Milk", effect: "HP +30" },
      { ingredient1: "Fruit", ingredient2: "Drink", effect: "Atk (S)" },
      { ingredient1: "Veggie", ingredient2: "Veggie", effect: "Def +10" },
      { ingredient1: "Veggie", ingredient2: "Milk", effect: "HP +10 Def +15" },
      { ingredient1: "Milk", ingredient2: "Milk", effect: "HP +20 Ice +3" },
    ],
  },
  {
    label: "X4",
    ingredients: [
      { name: "Dragon Foot", type: "Meat", selected: false },
      { name: "Gator Ribmeat", type: "Meat", selected: false },
      { name: "Princess Pork", type: "Meat", selected: false },
      { name: "Ancient Beans", type: "Bran", selected: false },
      { name: "Kokoto Rice", type: "Bran", selected: false },
      { name: "Megabagel", type: "Bran", selected: false },
      { name: "King Squid", type: "Fish", selected: false },
      { name: "Queen Shrimp", type: "Fish", selected: false },
      { name: "Pink Caviar", type: "Fish", selected: false },
      { name: "Burning Mango", type: "Fruit", selected: false },
      { name: "Lifejam", type: "Fruit", selected: false },
      { name: "Cannon Lettuce", type: "Veggie", selected: false },
      { name: "Rare Onion", type: "Veggie", selected: false },
      { name: "Scented Celery", type: "Veggie", selected: false },
      { name: "Royale Cheese", type: "Milk", selected: false },
      { name: "Blessed Wine", type: "Drink", selected: false }
    ],
    meals: [
      { ingredient1: "Meat", ingredient2: "Meat", effect: "HP +30" },
      { ingredient1: "Meat", ingredient2: "Fish", effect: "Stm +25 Wtr +5" },
      { ingredient1: "Meat", ingredient2: "Fruit", effect: "Atk (S) Fir +5" },
      { ingredient1: "Meat", ingredient2: "Milk", effect: "HP +40" },
      { ingredient1: "Meat", ingredient2: "Drink", effect: "Def +10 Ice +5" },
      { ingredient1: "Bran", ingredient2: "Bran", effect: "Stm +50" },
      { ingredient1: "Bran", ingredient2: "Veggie", effect: "Stm +25 Atk (S)" },
      { ingredient1: "Bran", ingredient2: "Milk", effect: "HP +30 Atk (S)" },
      { ingredient1: "Fish", ingredient2: "Fish", effect: "Atk (L)" },
      { ingredient1: "Fish", ingredient2: "Fruit", effect: "Def +20" },
      { ingredient1: "Fish", ingredient2: "Veggie", effect: "HP +20 Drg +3" },
      { ingredient1: "Fish", ingredient2: "Milk", effect: "Def +10 Thn +5" },
      { ingredient1: "Fruit", ingredient2: "Fruit", effect: "HP +10 Atk (L)" },
      { ingredient1: "Fruit", ingredient2: "Veggie", effect: "Stm +50" },
      { ingredient1: "Fruit", ingredient2: "Drink", effect: "HP +20 Def +15" },
      { ingredient1: "Veggie", ingredient2: "Veggie", effect: "Def +15" },
      { ingredient1: "Veggie", ingredient2: "Drink", effect: "HP +40" },
      { ingredient1: "Milk", ingredient2: "Drink", effect: "HP +20 Stm +25" }
    ],
  },
  {
    label: "X5",
    ingredients: [
      { name: "Bigmeat", type: "Meat", selected: false },
      { name: "Dragon Head", type: "Meat", selected: false },
      { name: "Dragon Tail", type: "Meat", selected: false },
      { name: "King Turkey", type: "Meat", selected: false },
      { name: "Gold Rice", type: "Bran", selected: false },
      { name: "Heaven Bread", type: "Bran", selected: false },
      { name: "Sould Beans", type: "Bran", selected: false },
      { name: "1000-Year Crab", type: "Fish", selected: false },
      { name: "Crimson Seabream", type: "Fish", selected: false },
      { name: "Hairy Tuna", type: "Fish", selected: false },
      { name: "Emerald Durian", type: "Fruit", selected: false },
      { name: "Demonshroom", type: "Veggie", selected: false },
      { name: "Fatty Tomato", type: "Veggie", selected: false },
      { name: "King Truffle", type: "Veggie", selected: false },
      { name: "Kirin Cheese", type: "Milk", selected: false },
      { name: "Goldenfish Brew", type: "Drink", selected: false }
    ],
    meals: [
      { ingredient1: "Meat", ingredient2: "Meat", effect: "HP +30" },
      { ingredient1: "Meat", ingredient2: "Fish", effect: "HP +20 Stm +50" },
      { ingredient1: "Meat", ingredient2: "Veggie", effect: "HP +40 Atk (L)" },
      { ingredient1: "Meat", ingredient2: "Milk", effect: "Stm +25 Def +15" },
      { ingredient1: "Meat", ingredient2: "Drink", effect: "Atk (S) Fir +5" },
      { ingredient1: "Bran", ingredient2: "Bran", effect: "Stm +50" },
      { ingredient1: "Bran", ingredient2: "Fish", effect: "HP +40 Def +20" },
      { ingredient1: "Bran", ingredient2: "Fruit", effect: "HP +30 Stm +25" },
      { ingredient1: "Bran", ingredient2: "Veggie", effect: "Stm +25 Atk (S)" },
      { ingredient1: "Bran", ingredient2: "Drink", effect: "HP +20 Wtr +20" },
      { ingredient1: "Fish", ingredient2: "Fish", effect: "Atk (L)" },
      { ingredient1: "Fish", ingredient2: "Fruit", effect: "Stm +50 Def +10" },
      { ingredient1: "Fish", ingredient2: "Veggie", effect: "Def +10 Ice +5" },
      { ingredient1: "Fruit", ingredient2: "Fruit", effect: "-----------" },
      { ingredient1: "Fruit", ingredient2: "Milk", effect: "HP +50 Drg +5" },
      { ingredient1: "Fruit", ingredient2: "Drink", effect: "Atk (S) Thn 5" },
      { ingredient1: "Veggie", ingredient2: "Veggie", effect: "Def +15" },
      { ingredient1: "Veggie", ingredient2: "Milk", effect: "Stm +25 Def +20" },
      { ingredient1: "Milk", ingredient2: "Milk", effect: "-----------" },
      { ingredient1: "Milk", ingredient2: "Drink", effect: "HP +50 Stm +50" }
    ],
  },
];

const emojisTypeIngredient = [
  { name: "Meat", emoji: "\u{1F356}" },       
  { name: "Bran", emoji: "\u{1F33E}" },       
  { name: "Fish", emoji: "\u{1F41F}" },       
  { name: "Fruit", emoji: "\u{1F34E}" },      
  { name: "Veggie", emoji: "\u{1F966}" },     
  { name: "Milk", emoji: "\u{1F95B}" },       
  { name: "Drink", emoji: "\u{1F964}" }   
];

const data = { tabData, emojisTypeIngredient };

export default data;